Replace QPalette::Background with QPalette::Window in AudioNoiseWidget::paintEvent()
I just had a FreeBSD build fail because AudioStats.cpp is using QPalette::Background, which apparently has been declared deprecated.

AudioStats.cpp:213:45: error: 'Background' is deprecated: Use QPalette::Window instead [-Werror,-Wdeprecated-declarations]
        paint.fillRect(rect(), pal.color(QPalette::Background));
                                                   ^

The Qt docs advise to use QPalette::Window instead (see https://doc.qt.io/qt-5/qpalette.html), so I went ahead and changed the code accordingly.